services:
  collector:
    image: otel/opentelemetry-collector:0.92.0
    command: ['--config=/etc/otel-collector-config.yaml']
    volumes:
      - './smoke-tests/collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml'
      - './smoke-tests/collector:/var/lib'
    ports:
      - '4318:4318'
